# Generated by Django 5.1.7 on 2025-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
